# Generated by Django 5.2.4 on 2025-07-16 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_grupo', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ubicacion_geografica', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'db_table': 'Grupos',
            },
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id_miembro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=10, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Pendiente', 'Pendiente')], default='Activo', max_length=50)),
            ],
            options={
                'verbose_name': 'Miembro',
                'verbose_name_plural': 'Miembros',
                'db_table': 'Miembros',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_evento', models.DateTimeField()),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('publico', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_grupo_responsable', models.ForeignKey(blank=True, db_column='id_grupo_responsable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.grupo')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'Eventos',
            },
        ),
        migrations.AddField(
            model_name='grupo',
            name='id_lider',
            field=models.ForeignKey(blank=True, db_column='id_lider', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_liderados', to='core.miembro'),
        ),
        migrations.CreateModel(
            name='Contribucion',
            fields=[
                ('id_contribucion', models.AutoField(db_column='id_contribucion', primary_key=True, serialize=False)),
                ('tipo_contribucion', models.CharField(db_column='tipo_contribucion', max_length=50)),
                ('cantidad', models.DecimalField(db_column='cantidad', decimal_places=2, max_digits=10)),
                ('fecha_contribucion', models.DateField(db_column='fecha_contribucion')),
                ('metodo_pago', models.CharField(db_column='metodo_pago', default='No especificado', max_length=50)),
                ('id_miembro', models.ForeignKey(db_column='id_miembro', on_delete=django.db.models.deletion.CASCADE, to='core.miembro')),
            ],
            options={
                'verbose_name': 'Contribución',
                'verbose_name_plural': 'Contribuciones',
                'db_table': 'Contribuciones',
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id_certificado', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_certificado', models.CharField(max_length=50)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('contenido_generado_texto', models.TextField(blank=True, null=True)),
                ('url_pdf', models.URLField(blank=True, max_length=255, null=True)),
                ('id_miembro', models.ForeignKey(db_column='id_miembro', on_delete=django.db.models.deletion.CASCADE, to='core.miembro')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'db_table': 'Certificados',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=50, unique=True)),
                ('contrasena', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultimo_login', models.DateTimeField(blank=True, null=True)),
                ('rol', models.CharField(blank=True, max_length=50, null=True)),
                ('id_miembro', models.ForeignKey(blank=True, db_column='id_miembro', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.miembro')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='AsistenciaEvento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asistencia', models.DateField()),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.evento')),
                ('id_miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.miembro')),
            ],
            options={
                'verbose_name': 'Asistencia a Evento',
                'verbose_name_plural': 'Asistencia a Eventos',
                'db_table': 'Asistencia_Eventos',
                'unique_together': {('id_miembro', 'id_evento')},
            },
        ),
        migrations.CreateModel(
            name='MiembroGrupo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_union', models.DateField(blank=True, null=True)),
                ('id_grupo', models.ForeignKey(db_column='id_grupo', on_delete=django.db.models.deletion.CASCADE, to='core.grupo')),
                ('id_miembro', models.ForeignKey(db_column='id_miembro', on_delete=django.db.models.deletion.CASCADE, to='core.miembro')),
            ],
            options={
                'verbose_name': 'Miembro de Grupo',
                'verbose_name_plural': 'Miembros de Grupos',
                'db_table': 'Miembros_Grupos',
                'unique_together': {('id_miembro', 'id_grupo')},
            },
        ),
    ]
