# Generated by Django 4.2.16 on 2025-07-17 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCertificado',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('plantilla_html', models.TextField(help_text='Plantilla HTML para el certificado')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('requiere_fecha_evento', models.BooleanField(default=False)),
                ('requiere_pastor', models.BooleanField(default=False)),
                ('requiere_testigos', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tipo de Certificado',
                'verbose_name_plural': 'Tipos de Certificados',
                'db_table': 'Tipos_Certificados',
            },
        ),
        migrations.AlterModelOptions(
            name='certificado',
            options={'ordering': ['-fecha_emision'], 'verbose_name': 'Certificado', 'verbose_name_plural': 'Certificados'},
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='contenido_generado_texto',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='url_pdf',
        ),
        migrations.AddField(
            model_name='certificado',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='contenido_personalizado',
            field=models.JSONField(default=dict, help_text='Datos específicos del certificado'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('emitido', 'Emitido'), ('anulado', 'Anulado')], default='borrador', max_length=20),
        ),
        migrations.AddField(
            model_name='certificado',
            name='fecha_evento_certificado',
            field=models.DateField(blank=True, help_text='Fecha del evento certificado (ej: bautismo)', null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='id_evento',
            field=models.ForeignKey(blank=True, help_text='Evento relacionado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.evento'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='numero_certificado',
            field=models.CharField(default='CERT-0001', help_text='Número único del certificado', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificado',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='pastor_firma',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='pastor_nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='testigo1_nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='testigo2_nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='usuario_creacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='tipo_certificado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipocertificado'),
        ),
    ]
