# Generated by Django 4.2.16 on 2025-07-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tipocertificado_alter_certificado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribucion',
            name='categoria',
            field=models.CharField(choices=[('diezmo', 'Diezmos'), ('ofrenda_culto', 'Ofrendas de Culto'), ('ofrenda_especial', 'Ofrendas Especiales'), ('donacion', 'Donaciones'), ('evento', 'Eventos'), ('gasto_operativo', 'Gastos Operativos'), ('gasto_ministerio', 'Gastos de Ministerio'), ('gasto_mantenimiento', 'Mantenimiento')], db_column='categoria', default='diezmo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contribucion',
            name='concepto',
            field=models.CharField(db_column='concepto', default='Contribución general', help_text='Descripción detallada del movimiento', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contribucion',
            name='es_ingreso',
            field=models.BooleanField(db_column='es_ingreso', default=True, help_text='True para ingresos, False para egresos'),
        ),
        migrations.AddField(
            model_name='contribucion',
            name='numero_recibo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='contribucion',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
