# Generated by Django 4.2.16 on 2025-07-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contribucion_categoria_contribucion_concepto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribucion',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta')], db_column='metodo_pago', default='efectivo', max_length=50),
        ),
        migrations.AlterField(
            model_name='contribucion',
            name='tipo_contribucion',
            field=models.CharField(choices=[('diezmo', 'Diezmo'), ('ofrenda', 'Ofrenda'), ('especial', 'Contribución Especial')], db_column='tipo_contribucion', max_length=50),
        ),
    ]
