# Generated by Django 5.2.4 on 2025-08-19 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_evento_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_familia', models.CharField(max_length=100)),
                ('meta_diezmo_mensual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('jefe_familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familia_liderada', to='core.miembro')),
                ('miembros', models.ManyToManyField(related_name='familias', to='core.miembro')),
            ],
            options={
                'verbose_name': 'Familia',
                'verbose_name_plural': 'Familias',
                'db_table': 'Familias',
            },
        ),
        migrations.CreateModel(
            name='PresupuestoAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('categoria', models.CharField(max_length=100)),
                ('monto_presupuestado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_ejecutado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Presupuestos_Anuales',
                'unique_together': {('año', 'categoria')},
            },
        ),
        migrations.CreateModel(
            name='ProyectoFinanciero',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proyecto', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('meta_financiera', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_recaudado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_inicio', models.DateField()),
                ('fecha_objetivo', models.DateField()),
                ('estado', models.CharField(choices=[('planificacion', 'En Planificación'), ('activo', 'Activo'), ('completado', 'Completado'), ('suspendido', 'Suspendido')], default='planificacion', max_length=20)),
                ('categoria_proyecto', models.CharField(choices=[('construccion', 'Construcción'), ('misiones', 'Misiones'), ('equipamiento', 'Equipamiento'), ('eventos', 'Eventos Especiales'), ('social', 'Acción Social')], max_length=100)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.miembro')),
            ],
            options={
                'verbose_name': 'Proyecto Financiero',
                'verbose_name_plural': 'Proyectos Financieros',
                'db_table': 'Proyectos_Financieros',
            },
        ),
    ]
